<?php
// $Id$

/**
 * @file
 * Use this module to learn about Drupal's menu system.
 */

/**
 * implementation of hook_perm().
 */
function menufun_perm(){
	return array('list points', 'upload points');
}

/**
 * Implementation of hook_menu().
 */
function menufun_menu(){
	$items['menufun'] = array(
		'title' => 'Furious Raid Points',
		'page callback' => 'menufun_hello',
		'access arguments' => array('list points'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['menufun/list'] = array(
		'title' => 'List Points',
		'access arguments' => array('list points'),
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => 0,
	);
	$items['menufun/upload'] = array(
		'title' => 'Upload FuriousRaid.lua',
		'access arguments' => array('upload points'),
		'page callback' => 'menufun_upload',
		'type' => MENU_LOCAL_TASK,
		'weight' => 1,
	);

	return $items;
}

/**
 * Page callback, uploading points
 */
function menufun_upload(){
	$output = t('Upload the FuriousRaid.lua file from:<br/> "World of Warcraft/WTF/Account/YOUR_ACCOUNT_NAME/SavedVariables/FuriousRaid.lua"');
	$output .= drupal_get_form('formexample_fruploadform');
	return $output;
}

/**
 *Define form
*/
function formexample_fruploadform(){
	$form['#attributes']['enctype'] = 'multipart/form-data';
	$form['frfile'] = array(
		'#title' => t('FuriousRaid.lua file'),
		'#type' => 'file',
		'#description' => t('Please attach the file here'),
		'#size' => 30,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return $form;
}

/**
 * handle post validation form submission
 */
function formexample_fruploadform_submit($form, &$form_state){
	$file = file_save_upload('frfile', $validators = array(), $dest = file_directory_path(), $replace = FILE_EXISTS_REPLACE);
	$error = file_set_status(&$file, $status = FILE_STATUS_PERMANENT);
	drupal_set_message(t($file->filepath));	
	menufun_phparray2table(menufun_lua2phparray($file));
}

/** 
 * import the lua2phparray file and convert our lua file to a php array
 */
function menufun_lua2phparray($fileobject){
	include 'lua2phparray.php';
	$frArray = array();
	$frArray = makePhpArray($fileobject->filepath);
	return $frArray;
}

/**
 * convert the expected array to an html table
 */
function menufun_phparray2table($frArray){
	$subset = array();
	$subset = $frArray['FuriousRaidDB']['account']['Karma'];
	$table = '<table>';
	foreach ($subset as $toon) {
		$table .= '<tr>';
		$table .= '<td>'.$toon['name'].'</td>';
		$table .= '<td>'.$toon['class'].'</td>';
		//break it down to just the karma array		
		$karma = $toon['karma'];
		foreach ($karma as $key => $value) {
			$table .= '<td>'.$key.': '.$value.'</td>';
		}
		$table .= '</tr>';
	}
	$table .= '</table>';
	file_save_data($table, file_directory_path().'/'.'frpoints.inc', $replace = FILE_EXISTS_REPLACE);
}
/**
 * Page callback, listing points.
 */
function menufun_hello(){
	$filename = 'frpoints.inc';
	$filename = file_directory_path().'/'.$filename;
	$output = file_get_contents($filename);
	return $output;
}

