<?php


/**
 * Implements hook_flush_caches().
 */
function migratedf_flush_caches() {
  migratedf_register_migrations();
}

/**
 * DownfallD2DMigration - USING migrate_d2d TO VASTLY SIMPLIFY
 */

function migratedf_register_migrations(){
  $common_arguments = array(
    'source_version' => 6,
    'group' => 'DownfallD2DMigration',
    'source_connection' => 'df6import',
    'source_database' => array(
      'driver' => 'mysql',
      'database' => 'downfall_d6_pristine',
      'username' => 'root', // Ideally this user has readonly access
      // Best practice: use a variable (defined by setting $conf in settings.php, or
      // with drush vset) for the password rather than exposing it in the code.
      // 'password' => variable_get('example_migrate_password', ''),
      'password' => 'root',
      'host' => 'localhost',
      'prefix' => 'demo_',
    ),
  // come back to format mappings
  // 'format_mappings' => array(
  //   '5' => 'markdown',
  // ),
    );

  /**
   * DownfallD2DMigration - ROLES
   */

  $role_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DRoles',
    'description' => t('Import Drupal 6 roles'),
    // 'role_mappings' => array(
    //   'Fan Club' => 'fan club member',
    // ),
  );
  Migration::registerMigration('DrupalRole6Migration',
    $role_arguments['machine_name'], $role_arguments);

  /**
   * DownfallD2DPictures - USER PICTURES
   */
  $picture_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DPictures',
    'description' => t('Import Drupal 6 picture files'),
    'default_uid' => 1,
    'source_dir' => 'sites/www.downfallguild.org/files/',
    'destination_dir' => 'public://pictures',
  );
  Migration::registerMigration('DrupalPicture6Migration',
    $picture_arguments['machine_name'], $picture_arguments);

  /**
   * DownfallD2DMigration - USERS
   */

  $user_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DUser',
    'description' => t('Migration of users from Drupal 6'),
    'role_migration' => 'DownfallD2DRoles',
    'picture_migration' => 'DownfallD2DPictures',
    'soft_dependencies' => array('DownfallD2DPictures'),
  );

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalUser6Migration',
    $user_arguments['machine_name'], $user_arguments);

  /**
   * DownfallD2DMigration - FILES
   */

  $file_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DFiles',
    'description' => t('Import Drupal 6 files'),
    'user_migration' => 'DownfallD2DUser',
    'default_uid' => 1,
    'source_dir' => 'sites/www.downfallguild.org/files/',
    'destination_dir' => 'public://',
  );
  Migration::registerMigration('DrupalFile6Migration',
    $file_arguments['machine_name'], $file_arguments);

  /**
   * DownfallD2DMigration - VOCABULARY / Forums
   */

  $forums_term_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DTermForums',
    'description' => t('Import Drupal 6 forums terms into forums terms'),
    'source_vocabulary' => '3',  // "forums category" vocabulary
    'destination_vocabulary' => 'forums',
  );
  Migration::registerMigration('DrupalTerm6Migration',
    $forums_term_arguments['machine_name'], $forums_term_arguments);

  /**
   * DownfallD2DMigration - VOCABULARY / WoW
   */

  $wow_term_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DTermWoW',
    'description' => t('Import Drupal 6 wow terms into wow terms'),
    'source_vocabulary' => '5',  // "forums category" vocabulary
    'destination_vocabulary' => 'wow',
  );
  Migration::registerMigration('DrupalTerm6Migration',
    $wow_term_arguments['machine_name'], $wow_term_arguments);

  /**
   * DownfallD2DMigration - VOCABULARY / Image Galleries
   */

  $gallery_term_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DTermGallery',
    'description' => t('Import Drupal 6 gallery terms into gallery terms'),
    'source_vocabulary' => '8',  // "forums category" vocabulary
    'destination_vocabulary' => 'gallery',
  );
  Migration::registerMigration('DrupalTerm6Migration',
    $gallery_term_arguments['machine_name'], $gallery_term_arguments);

  /**
   * DownfallD2DMigration - Menus
   */

  $menu_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DMenus',
    'description' => t('Import Drupal 6 menus'),
  );
  Migration::registerMigration('DrupalMenu6Migration',
    $menu_arguments['machine_name'], $menu_arguments);

  /**
   * DownfallD2DMigration - Menu Links
   */

  $menu_link_arguments = $common_arguments + array(
    'machine_name' => 'DownfallD2DMenuLinks',
    'description' => t('Import Drupal 6 menu links'),
    'menu_migration' => 'DownfallD2DMenus',
    'node_migrations' => array('DownfallD2DNodeBook'),
    // 'term_migrations' => array('ExamplePhotoTerm', 'ExampleVideoTerm'),
  );

  Migration::registerMigration('DrupalMenuLinks6Migration',
    $menu_link_arguments['machine_name'], $menu_link_arguments);

  /**
   * DownfallD2DMigration - NODES
   */

  // Use another layer of common arguments to reduce duplication
  $node_arguments = $common_arguments + array(
    'user_migration' => 'DownfallD2DUser',
    'default_uid' => 1,
  );

  /**
   * DownfallD2DMigration - NODES / Book
   */

  $book_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeBook',
    'description' => t('Import Drupal 6 book nodes'),
    'source_type' => 'book',
    'destination_type' => 'book',
    'dependencies' => array('DownfallD2DTermWoW'),
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallBookMigration',
    $book_node_arguments['machine_name'], $book_node_arguments);

  /**
   * DownfallD2DMigration - NODES / Blog
   */

  $blog_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeBlog',
    'description' => t('Import Drupal 6 blog nodes'),
    'source_type' => 'blog',
    'destination_type' => 'blog',
    'dependencies' => array('DownfallD2DTermWoW'),
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallGenericWowTermNodeMigration',
    $blog_node_arguments['machine_name'], $blog_node_arguments);

  /**
   * DownfallD2DMigration - NODES / Forums
   */

  $forum_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeForum',
    'description' => t('Import Drupal 6 forum nodes'),
    'source_type' => 'forum',
    'destination_type' => 'forum',
    'dependencies' => array('DownfallD2DTermForums'),
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallForumMigration',
    $forum_node_arguments['machine_name'], $forum_node_arguments);

  /**
   * DownfallD2DMigration - NODES / Pages
   */

  $page_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodePage',
    'description' => t('Import Drupal 6 page nodes'),
    'source_type' => 'page',
    'destination_type' => 'article',
    'dependencies' => array('DownfallD2DTermWoW'),
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallGenericWowTermNodeMigration',
    $page_node_arguments['machine_name'], $page_node_arguments);

  /**
   * DownfallD2DMigration - NODES / story -> article
   */

  $story_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeStory',
    'description' => t('Import Drupal 6 story nodes'),
    'source_type' => 'story',
    'destination_type' => 'article',
    'dependencies' => array('DownfallD2DTermWoW'),
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallGenericWowTermNodeMigration',
    $story_node_arguments['machine_name'], $story_node_arguments);

  /**
   * DownfallD2DMigration - NODES / raidevent -> event
   */

  $date_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeDate',
    'description' => t('Import Drupal 6 date nodes'),
    'source_type' => 'raidevent',
    'destination_type' => 'event',
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallDateNodeMigration',
    $date_node_arguments['machine_name'], $date_node_arguments);

  /**
   * DownfallD2DMigration - NODES / event -> event
   */

  $olddate_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeDateOld',
    'description' => t('Import Drupal 6 old event nodes'),
    'source_type' => 'event',
    'destination_type' => 'event',
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallOldEventNodeMigration',
    $olddate_node_arguments['machine_name'], $olddate_node_arguments);

  /**
   * DownfallD2DMigration - NODES / guild_app
   */

  $guildapp_node_arguments = $node_arguments + array(
    'machine_name' => 'DownfallD2DNodeGuildApp',
    'description' => t('Import Drupal 6 guild apps'),
    'source_type' => 'guild_app',
    'destination_type' => 'guild_app',
  );
  // Note we use a custom class here so we can map the term references and
  // other fields - see "Extending migrate_d2d classes" below.
  Migration::registerMigration('DownfallGuildAppsMigration',
    $guildapp_node_arguments['machine_name'], $guildapp_node_arguments);

}

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function migratedf_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}